FROM openjdk:21-jdk-slim AS build
WORKDIR /app
COPY . .

RUN mkdir /app/classes
RUN javac -d /app/classes src/main/java/com/example/SimpleWebServer.java

# Second Stage
FROM openjdk:21-jdk-slim
WORKDIR /app

COPY --from=build /app/classes .

EXPOSE 8080
CMD ["java", "com.example.SimpleWebServer"]