FROM eclipse-temurin:21-jdk-noble AS build
WORKDIR /app
COPY . .

RUN mkdir /app/classes
RUN javac -d /app/classes src/main/java/com/example/SimpleWebServer.java

# Second Stage
FROM eclipse-temurin:21-jre-noble
WORKDIR /app

COPY --from=build /app/classes .

EXPOSE 8080
CMD ["java", "com.example.SimpleWebServer"]