FROM openjdk:17-jdk-slim
WORKDIR /app

# TODO: Task 3.2 - Copy the project source code into the working directory. Then, add a command to compile the Java source file located at src/main/java/com/example/SimpleWebServer.java.


# TODO: Task 3.3 - Expose port 8080 to allow traffic to the web server. Then, specify the default command to run the application when the container starts. The main class is com.example.SimpleWebServer and the classpath is src/main/java.

